<a href="https://colab.research.google.com/github/yogitamittal93/deep-learning-practice/blob/main/twitterSentimentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import spacy
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
import pandas as pd
col_names = ['ID', 'Entity', 'Sentiment', 'Tweet_Content']
data = pd.read_csv('/content/twitter_training.csv', names=col_names, header=None)
data.head()

,ID,Entity,Sentiment,Tweet_Content
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...

In [ ]:
data.tail(20)

,ID,Entity,Sentiment,Tweet_Content
74662,9197,Nvidia,Neutral,Nvidia therefore doesn ’ t want to give up its...
74663,9197,Nvidia,Neutral,is doesn’t should I give up its password ‘cryp...
74664,9198,Nvidia,Negative,Nvidia really delayed the 3070 2 weeks .
74665,9198,Nvidia,Negative,Nvidia really delayed the 3070 by 2 weeks.
74666,9198,Nvidia,Negative,Nvidia did delay by 3070 2 weeks.
74667,9198,Nvidia,Negative,Nvidia really delayed the 3070 several weeks.
74668,9198,Nvidia,Negative,Nvidia really only delayed the 3070 2 flight w...
74669,9198,Nvidia,Negative,Nvidia really delayed the next 2 weeks.
74670,9199,Nvidia,Positive,Let no elim go unnoticed. . . . NVIDIA Highlig...
74671,9199,Nvidia,Positive,t let Elim go unnoticed.... NVIDIA Highlights ...
74672,9199,Nvidia,Positive,Let no elite go unnoticed... NVIDIA Highlights...
74673,9199,Nvidia,Positive,Let no elim go unnoticed.... NVIDIA Highlights...
74674,9199,Nvidia,Positive,Let a no information elim that go unnoticed......
74675,9199,Nvidia,Positive,<unk> my elim be no.... NVIDIA Highlights Pict...
74676,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74677,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74678,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74679,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74680,9200,Nvidia,Positive,Just realized between the windows partition of...
74681,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['sentiment_encoded'] = le.fit_transform(data['Sentiment'])

In [ ]:
data.head()

,ID,Entity,Sentiment,Tweet_Content,sentiment_encoded
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...,3
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...,3
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...,3
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...,3
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...,3

In [ ]:
def preprocess(text):
  doc=nlp(text)
  return " ".join([
      token.lemma_.lower()
      for token in doc
      if not token.is_stop and not token.is_punct
  ])

In [ ]:
nlp=spacy.load('en_core_web_sm')
vectorizer=TfidfVectorizer()
rev=[preprocess(str(text)) for text in data['Tweet_Content']]
X=vectorizer.fit_transform(rev)
y=data['sentiment_encoded']

In [ ]:
x_train, x_test, y_train, y_test=train_test_split(X, y, test_size=0.25, random_state=42)

In [ ]:
model=SVC()

In [ ]:
model.fit(x_train, y_train)

SVC()

In [ ]:
accuracy_score(y_test, model.predict(x_test))

0.9084141181511435